import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import Link from "next/link";
import { AppNav } from "@/components/app-nav";

export const metadata: Metadata = {
  title: "xiv mitplan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="px-4 py-2 flex justify-between align-middle">
            <nav className="flex gap-4">
              <Link href="/" className="text-2xl">
                xiv mitplan
              </Link>
              <AppNav />
            </nav>
            <ThemeToggle />
          </header>
          <main className="px-4">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
